sdz_admin:
    resource: "@SdzAdminBundle/Resources/config/routing.yml"
    prefix:   /

sdz_user:
    resource: "@SdzUserBundle/Resources/config/routing.yml"
    prefix:   /user

sdz_soap:
    resource: "@SdzSoapBundle/Resources/config/routing.yml"
    prefix:   /

sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /blog
    
_besimple_soap:
    resource: "@BeSimpleSoapBundle/Resources/config/routing/webservicecontroller.xml"
    prefix:   /ws

# route Sonata admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin