services:
    sdz_user.registration.form.type:
        class: Sdz\Bundle\UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sdz_user_registration }
